version: '3'

services:
  client:
    build: ./src/client
    ports:
      - 8080:8080
    volumes:
      - ./src/client:/app
  proxy:
    depends_on:
      - client
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./src/proxy:/etc/nginx/conf.d
  ngrok:
    command: ngrok http proxy:80
    depends_on:
      - proxy
    image: wernight/ngrok
    ports:
      - 4040:4040
